### ISSUE TITLE
Docs on how to use options?

### ISSUE THREAD

**Issue by Xavvi** [mad-genius/mg-space#7]
Hello,

Love this plugin. I've been using it with the default options up to now - with 4 columns on desktop, which is the default set in the main script. Are there any docs or examples of how to change this on a grid by grid basis during instantiation? 

Thanks

**Comment by bryce-mullican** [comment]
Hi, sorry for the slow response. To override any of the defaults just pass in an object and set the value of the property you wish to override to the necessary value. 
`        $('.your-target').mgSpace({
            breakpointColumns: [
                {
                    breakpoint: 0,
                    column: 1
                },
                {
                    breakpoint: 400,
                    column: 2
                },
                {
                    breakpoint: 600,
                    column: 3
                }                
            ]
        });
`
If this isn't what you were looking for please let me know.
Thanks
Bryce

**Comment by Xavvi** [comment]
Hi Bryce,

That's exactly what I was after. Thanks very much.
